-- Export of table: viewpoint_ai_summaries
-- Exported at: 2026-01-15T15:55:55.477420
-- Total rows: 5

INSERT INTO viewpoint_ai_summaries (id, viewpoint_id, history_summary, search_summary, season_info, visual_tags, source, created_at, updated_at) VALUES (1, 62323, 'Rupnagar is a city in Punjab, India, known for its significance as an Indus Valley civilization site. It features an archaeological museum that showcases artifacts from the Harappan period to medieval times.', 'Rupnagar is an important historical site in Punjab, India, recognized for its archaeological significance and as a city of the Indus Valley civilization. The city also hosts a museum displaying ancient artifacts.', '{"season": "unknown", "evidence": {"history_source": "sections", "visual_evidence": "aerial view of the city layout"}, "confidence": 0.5}'::jsonb, '["attraction"]'::jsonb, 'gpt_4o_mini_image_history', '2026-01-15 15:42:53.946788+11:00', '2026-01-15 15:54:57.547376+11:00');
INSERT INTO viewpoint_ai_summaries (id, viewpoint_id, history_summary, search_summary, season_info, visual_tags, source, created_at, updated_at) VALUES (2, 62324, 'K2, known as 乔戈里峰, is one of the highest mountains in the world and a popular destination for climbers. It is renowned for its challenging ascent and stunning views.', 'K2, or 乔戈里峰, is a prominent snow-covered peak that attracts climbers and adventurers. Its challenging terrain and breathtaking scenery make it a notable attraction.', '{"season": "winter", "evidence": {"history_source": "name_inference", "visual_evidence": "snow-covered mountain landscape with fog"}, "confidence": 0.9}'::jsonb, '["snow_peak", "foggy", "attraction"]'::jsonb, 'gpt_4o_mini_image_history', '2026-01-15 15:42:59.063702+11:00', '2026-01-15 15:55:02.332421+11:00');
INSERT INTO viewpoint_ai_summaries (id, viewpoint_id, history_summary, search_summary, season_info, visual_tags, source, created_at, updated_at) VALUES (3, 62325, 'Amarkantak is a pilgrim town in Madhya Pradesh, India, known for its unique natural heritage. It is the meeting point of the Vindhya and Satpura Ranges and is the origin of several rivers, including the Narmada.', 'Amarkantak is a significant pilgrimage site in India, renowned for its natural beauty and as the source of major rivers. The region''s unique geography makes it a notable attraction.', '{"season": "unknown", "evidence": {"history_source": "sections", "visual_evidence": "aerial view of the town and surrounding landscape"}, "confidence": 0.5}'::jsonb, '["attraction"]'::jsonb, 'gpt_4o_mini_image_history', '2026-01-15 15:43:04.891706+11:00', '2026-01-15 15:55:08.075446+11:00');
INSERT INTO viewpoint_ai_summaries (id, viewpoint_id, history_summary, search_summary, season_info, visual_tags, source, created_at, updated_at) VALUES (4, 62326, 'Sohra, also known as Cherrapunji, is a notable attraction known for its scenic beauty and unique weather patterns. It is often recognized for its lush landscapes and rich cultural heritage.', 'Sohra (Cherrapunji) is an attraction celebrated for its stunning landscapes and cultural significance. Visitors can explore its natural beauty and experience its unique weather.', '{"season": "unknown", "evidence": {"history_source": "name_inference", "visual_evidence": "aerial view of a landscape with urban and green areas"}, "confidence": 0.5}'::jsonb, '["attraction"]'::jsonb, 'gpt_4o_mini_image_history', '2026-01-15 15:43:11.830797+11:00', '2026-01-15 15:55:13.401777+11:00');
INSERT INTO viewpoint_ai_summaries (id, viewpoint_id, history_summary, search_summary, season_info, visual_tags, source, created_at, updated_at) VALUES (5, 62327, 'Shillong is a hill station and the capital of Meghalaya, India, known for its scenic rolling hills that reminded the British of Scotland, earning it the nickname ''Scotland of the East.''', 'Shillong is a picturesque hill station in India, celebrated for its lush landscapes and vibrant culture. It is often referred to as the ''Scotland of the East'' due to its stunning hills.', '{"season": "unknown", "evidence": {"history_source": "sections", "visual_evidence": "aerial view of a densely populated area with greenery"}, "confidence": 0.5}'::jsonb, '["sunny", "attraction"]'::jsonb, 'gpt_4o_mini_image_history', '2026-01-15 15:43:18.287142+11:00', '2026-01-15 15:55:19.565062+11:00');
